name: Archive Nightscout

# Run this workflow once a month, or when invoked
on:
  schedule:
    - cron: '20 4 10 * *' # https://crontab.guru/#20_4_10_*_*
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    container:
      image: mongo
      options: --user root

    steps:
      - name: Export records from source Mongo DB
        env:
          SOURCE: ${{secrets.SOURCE}}
        run: mongodump --out /backups $SOURCE
        
      - name: Upload records to destination Mongo DB
        env: 
          DEST: ${{secrets.DEST}}
        run: mongorestore --quiet --dir=/backups $DEST
