name: Archive Nightscout

# Run this workflow once a month, or when invoked
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    container:
      image: mongo
      options: --user root

    steps:
      # - uses: actions/checkout@v3

      - name: Export records from source Mongo DB
        env:
          SOURCE: ${{secrets.SOURCE}}
        run: mongodump --out /backups $SOURCE
        
      - name: Upload records to destination Mongo DB
        env: 
          DEST: ${{secrets.DEST}}
        run: mongorestore --dir=/backups $DEST
